# Example configuration with command layers
# This shows how to configure command layers for the octomind tool

[embedding_provider]
provider = "FastEmbed"

[fastembed]
code_model = "all-MiniLM-L6-v2"
text_model = "all-MiniLM-L6-v2"

[graphrag]
enabled = false
description_model = "openrouter:openai/gpt-4.1-nano"
relationship_model = "openrouter:openai/gpt-4.1-nano"

# Provider API keys
[providers.openrouter]
# api_key can be set here or via OPENROUTER_API_KEY environment variable

# Developer role configuration
[developer.config]
model = "openrouter:anthropic/claude-sonnet-4"
enable_layers = true
log_level = "info"
system = "You are an Octomind AI developer assistant with full access to development tools."

[developer.mcp]
enabled = true

[[developer.mcp.servers]]
enabled = true
name = "developer"
server_type = "developer"

[[developer.mcp.servers]]
enabled = true
name = "filesystem"
server_type = "filesystem"

# Command layers for developer role
[developer.commands.estimate]
name = "estimate"
enabled = true
model = "openrouter:openai/gpt-4.1-mini"
system_prompt = """You are a project estimation expert. Analyze the work done or discussed in the conversation and provide estimates for:

1. Time required for completion
2. Complexity assessment
3. Potential challenges
4. Suggested next steps

Be specific and practical in your estimates. Consider the context of the development work."""
temperature = 0.2
input_mode = "Last"

[developer.commands.estimate.mcp]
enabled = false

[developer.commands.query_processor]
name = "query_processor"
enabled = true
# No model specified - will use session model
system_prompt = """You are a query processor that improves and clarifies user requests.
Analyze the input and make it more specific and actionable for development work."""
temperature = 0.2
input_mode = "Last"

[developer.commands.query_processor.mcp]
enabled = false

[developer.commands.review]
name = "review"
enabled = true
model = "openrouter:anthropic/claude-3.5-sonnet"
system_prompt = """You are a code review expert. Analyze the recent work and provide:

1. Code quality assessment
2. Potential improvements
3. Best practices recommendations
4. Security considerations
5. Performance optimization suggestions

Focus on constructive feedback that helps improve the codebase."""
temperature = 0.1
input_mode = "All"

[developer.commands.review.mcp]
enabled = true
servers = ["core"]
allowed_tools = ["text_editor", "semantic_code"]

# Assistant role configuration
[assistant.config]
model = "openrouter:anthropic/claude-3.5-haiku"
enable_layers = false
system = "You are a helpful assistant."

[assistant.mcp]
enabled = false

# Assistant role command layers (simpler examples)
[assistant.commands.summarize]
name = "summarize"
enabled = true
system_prompt = "You are a summarization expert. Provide a clear, concise summary of the conversation or content."
temperature = 0.2
input_mode = "All"

[assistant.commands.summarize.mcp]
enabled = false

# Global command layers (fallback for any role)
[commands.help]
name = "help"
enabled = true
system_prompt = "You are a helpful assistant. Provide guidance and help based on the user's request."
temperature = 0.3
input_mode = "Last"

[commands.help.mcp]
enabled = false

# Legacy openrouter configuration for backward compatibility
[openrouter]
model = "openrouter:anthropic/claude-sonnet-4"
enable_layers = false
log_level = "none"
