# Simple command layers example for octomind

# Provider configuration
[providers.openrouter]
# Set your API key via OPENROUTER_API_KEY environment variable
# or uncomment and set it here:
# api_key = "your-api-key-here"

# Developer role configuration with command layers
[developer.config]
model = "openrouter:anthropic/claude-sonnet-4"
enable_layers = true

[developer.mcp]
enabled = true

[[developer.mcp.servers]]
enabled = true
name = "developer"
server_type = "developer"

[[developer.mcp.servers]]
enabled = true
name = "filesystem"
server_type = "filesystem"

# Simple estimate command for developers
[developer.commands.estimate]
name = "estimate"
enabled = true
model = "openrouter:openai/gpt-4.1-mini"
system_prompt = """You are a project estimation expert. Based on the conversation context, provide estimates for:

1. **Time required**: How long this work might take
2. **Complexity**: Technical difficulty level (1-5)
3. **Dependencies**: What needs to be done first
4. **Risks**: Potential challenges or blockers

Be specific and practical. Consider the scope of work discussed."""
temperature = 0.2
input_mode = "Last"

[developer.commands.estimate.mcp]
enabled = false

# Query improvement command (system layer equivalent)
[developer.commands.query_processor]
name = "query_processor"
enabled = true
system_prompt = """You are a query processor that improves and clarifies user requests.
Analyze the input and make it more specific and actionable for development work.
Provide a clearer, more detailed version of the request."""
temperature = 0.2
input_mode = "Last"

[developer.commands.query_processor.mcp]
enabled = false